version: "3"

tasks:
  serial-test:
    aliases: ["st"]
    dir: ./tester
    cmds:
      - go test

  flash:
    aliases: ["f"]
    cmds:
      - tinygo flash -target=pico

  flash-monitor:
    aliases: ["fm"]
    cmds:
      - tinygo flash -target=pico -monitor
