version: "3"

tasks:
  serial-test:
    aliases: ["st"]
    dir: ./tester
    cmds:
      - go test

  flash:
    aliases: ["f"]
    cmds:
      - tinygo flash -target=pico ./firmware

  flash-monitor:
    aliases: ["fm"]
    cmds:
      - tinygo flash -target=pico -monitor ./firmware

  build:
    aliases: ["b"]
    cmds:
      - tinygo build -o .build/auto-rost.elf -target=pico ./firmware

  run:
    aliases: ["r"]
    env:
      TWCHART_ADDR: http://server.local:8087
    cmds:
      - go run cmd/auto-roast/main.go
